language: java
os: linux
dist: bionic

services:
 - docker
  
before_install:
 - export BINDIR=$TRAVIS_BUILD_DIR/binaries
 - mkdir -p $BINDIR
 - docker build . -f Dockerfile -t ffmpeg-image 
 - docker run -v $BINDIR:/output --name ffmpeg --rm -it ffmpeg-image
 - mkdir -p natives-free/binaries/linux64 && mv $BINDIR/release/linux64/free/*.* $_
 - mkdir -p natives-free/binaries/windows64 && mv $BINDIR/release/windows64/free/*.* $_
 - mkdir -p natives-full/binaries/linux64 && mv $BINDIR/release/linux64/full/*.* $_
 - mkdir -p natives-full/binaries/windows64 && mv $BINDIR/release/windows64/full/*.* $_
 
script:
 - ./gradlew bintrayUpload
 